Feature products component
idnol/ui-power-pulse pull request #12
Opened 2024-03-04 07:17 UTC by oxananazaruk

Привіт!
Я забрала контейнер із AppLayout і додала в себе на сторінці в середині секції, як ми і говорили.
Стилізацію селекту ще не переписала і ще не дописала запит за продукктами. Зробдю це вже в новій гілці.

2024-03-04 07:27 UTC, idnol requested changes
Трохи не так ти зробила, коли буде час давай разом подивимось і вирішимо, поки не приймаю

2024-03-04 07:27 UTC, idnol requested changes

2024-03-04 07:27 UTC, idnol commented on src/components/AppLayout/AppLayout.jsx
> -        <div className='container'>
тут є проблеми

2024-03-04 07:32 UTC, oxananazaruk commented on src/components/AppLayout/AppLayout.jsx
> -        <div className='container'>
Добре. Я можу десь в 16.00 або пізніше.
Ти околи зможеш?

2024-03-06 11:24 UTC, idnol approved these changes

2024-03-06 11:24 UTC, merged